CXX = g++ -O2 -Wall 

all: GenerateProportion EstimateTrueCount FindNeighboursWithQual \
	AverageTagsQuals_27 AverageTagsQuals_36 PickBaseQual \
    AverageTagsQuals_17 \
    AverageTagsQuals_24 \
    AverageTagsQuals_28 \
    AverageTagsQuals_30 \
    AverageTagsQuals_31 \
    AverageTagsQuals_32 \
    AverageTagsQuals_33 \
    AverageTagsQuals_34 \
    AverageTagsQuals_35 \
    AverageTagsQuals_37 \
    AverageTagsQuals_38 \
    AverageTagsQuals_39 \
    AverageTagsQuals_40 \
    AverageTagsQuals_41 \
    AverageTagsQuals_42 \
    AverageTagsQuals_43 \
    AverageTagsQuals_44 \
    AverageTagsQuals_45 \
    AverageTagsQuals_46 \
    AverageTagsQuals_47 \
    AverageTagsQuals_48 \
    AverageTagsQuals_49 \
    AverageTagsQuals_50 \
    AverageTagsQuals_51 \
    AverageTagsQuals_52 \
    AverageTagsQuals_53 \
    AverageTagsQuals_54 \
    AverageTagsQuals_55 \
    AverageTagsQuals_56 \
    AverageTagsQuals_57 \
    AverageTagsQuals_58 \
    AverageTagsQuals_59 \
    AverageTagsQuals_60 \
    AverageTagsQuals_61 \
    AverageTagsQuals_62 \
    AverageTagsQuals_63 \
    AverageTagsQuals_64 \
    AverageTagsQuals_72 \
    AverageTagsQuals_73 \
    AverageTagsQuals_75 \
    AverageTagsQuals_76 \
    AverageTagsQuals_80 \
    AverageTagsQuals_87 \
    AverageTagsQuals_100\
    AverageTagsQuals_27_tag_prb\
    AverageTagsQuals_36_tag_prb


FindNeighboursWithQual: FindNeighboursWithQual.cc Utilities.cc
	$(CXX)   $^ -o $@

GenerateProportion: GenerateProportion.cc Utilities.cc
	$(CXX)   $^ -o $@

PickBaseQual: PickBaseQual.cc 
	$(CXX)   $^ -o $@

AverageTagsQuals_27_tag_prb: AverageTagsQuals_27_tag_prb.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_36_tag_prb: AverageTagsQuals_36_tag_prb.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_100: AverageTagsQuals_100.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_17: AverageTagsQuals_17.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_24: AverageTagsQuals_24.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_30: AverageTagsQuals_30.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_32: AverageTagsQuals_32.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_33: AverageTagsQuals_33.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_34: AverageTagsQuals_34.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_35: AverageTagsQuals_35.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_51: AverageTagsQuals_51.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_52: AverageTagsQuals_52.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_53: AverageTagsQuals_53.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_54: AverageTagsQuals_54.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_55: AverageTagsQuals_55.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_56: AverageTagsQuals_56.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_57: AverageTagsQuals_57.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_58: AverageTagsQuals_58.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_59: AverageTagsQuals_59.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_60: AverageTagsQuals_60.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_61: AverageTagsQuals_61.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_62: AverageTagsQuals_62.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_63: AverageTagsQuals_63.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_64: AverageTagsQuals_64.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_72: AverageTagsQuals_72.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_73: AverageTagsQuals_73.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_75: AverageTagsQuals_75.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_76: AverageTagsQuals_76.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_80: AverageTagsQuals_80.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_87: AverageTagsQuals_87.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_27: AverageTagsQuals_27.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_28: AverageTagsQuals_28.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_36: AverageTagsQuals_36.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_37: AverageTagsQuals_37.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_38: AverageTagsQuals_38.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_39: AverageTagsQuals_39.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_40: AverageTagsQuals_40.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_41: AverageTagsQuals_41.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_42: AverageTagsQuals_42.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_43: AverageTagsQuals_43.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_44: AverageTagsQuals_44.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_45: AverageTagsQuals_45.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_46: AverageTagsQuals_46.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_47: AverageTagsQuals_47.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_48: AverageTagsQuals_48.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_49: AverageTagsQuals_49.cc
	$(CXX)   $^ -o $@
AverageTagsQuals_50: AverageTagsQuals_50.cc
	$(CXX)   $^ -o $@

EstimateTrueCount: EstimateTrueCount.cc Utilities.cc
	$(CXX)   $^ -o $@

